# Generated by Django 3.2 on 2024-04-05 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='protects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protect_name', models.CharField(max_length=100)),
                ('prize', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('size', models.CharField(choices=[('small', 'S'), ('medium', 'M'), ('large', 'L')], max_length=30)),
                ('quentity', models.IntegerField()),
                ('bio', models.TextField(blank=True, max_length=300)),
                ('image', models.ImageField(null=True, upload_to='photos/protects')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
